module.exports = [
  'CHANGED_NAME',
  'CHANGED_CP',
  'CHANGED_HP',
  'CHANGED_STARDUST',
  'CHANGED_LEVEL',
  'CHANGED_TRAINER_LEVEL',
  'RESULTS_CALCULATED',
  'RESULTS_RESET',
  'VALUES_RESET',

  'TEAM_SELECTED',
  'APPRAISAL_IV_RANGE_SET',
  'APPRAISAL_ATTR_TOGGLED',
  'APPRAISAL_STAT_SET',

  'MOVES_CHANGED',
  'POKEMON_CHANGED',
  'DEX_TEXT_CHANGED',

  'POKEMON_CHECKED',
  'SEARCHES_LOADED',
]
